# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'Potaxito' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Potaxito
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Functions'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Google-Maps-iOS-Utils'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'JGProgressHUD'

end
